version: "2.1"

services:
  zeppelin:
      image: dylanmei/zeppelin
      ports:
          - "9002:8080"
      networks:
        spark-net:
          ipv4_address: 172.20.0.10

networks:
  spark-net:
    external:
      name: spark-net