version: "2.1"

services:
  zeppelin:
      build: .
      ports:
        - "9002:8080"
      networks:
        spark-net:
          ipv4_address: 172.20.0.10
      volumes:
        - /c/Users/zeeppelin/notebook/:/data/notebook/    
      environment:
        - ZEPPELIN_MEM=-Xmx1024m
        - ZEPPELIN_NOTEBOOK_DIR=/data/notebook

networks:
  spark-net:
    external:
      name: spark-net