version: '3'
services:
  spark:
    image: jupyter/pyspark-notebook
    ports:
      - "9001:8888"
      - "4040-4080:4040-4080"
    volumes:
      - /c/Users/notebook/:/home/jovyan/work/notebooks/
    networks:
      devnet:
        ipv4_address: 172.19.0.30

networks:
  devnet:
    external:
      name: devnet