    
version: '2'
services:

  spark-master:
    build: .
    image: produktion/jupyter-pyspark
    ports:
      - 7077:7077
      - 8080:8080
      - 6066:6066
    command: ["/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]

  jupyter:
    build: .
    image: produktion/jupyter-pyspark
    ports:
      - 9001:8888
    volumes:
      - ./work:/home/jovyan/work

  spark-worker:
    # Example for starting and connecting worker to spark master
    build: .
    image: produktion/jupyter-pyspark
    volumes:
      - ./worker:/scratch
    environment:
      - SPARK_WORKER_DIR=/scratch
    command: ["/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master